#!/usr/bin/perl
use strict;
use warnings;

use LWP::UserAgent;
use Data::Dumper;
use Getopt::Long;
use JSON::XS;
use URI::URL;
use Set::Object qw( set );
require Encode;
use Encode qw( encode decode );

binmode STDOUT, ":utf8";
binmode STDIN, ":utf8";
binmode STDERR, ":utf8";

my $ua = LWP::UserAgent->new;
$ua->timeout(10);
$ua->env_proxy;


my @q = qw( http://news.ycombinator.com );
my $seen = Set::Object->new();
while(@q) {
	print $seen->size,"\n";
	my $response = $ua->get(pop(@q));
	if ($response->is_success) {
		my @matches = ( $response->decoded_content =~ /href\s*=\s*"([^"]*)"/g );
		foreach (@matches) {
			my $link = url($_,$response->base)->abs->as_string;
			if($seen->insert($link)) {
				#print $link,"\n";
				print Dumper @q;
				unshift(@q,$link);
			}
		}

	} else {
		die $response->status_line;
	}
}
